//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beispiel_03
{
    using Microsoft.AspNetCore.Mvc;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Auto
    {
        public long Id { get; set; }
        public string Marke { get; set; }
        
        public decimal Kilometerstand { get; set; }
        public System.DateTime Herstellungsdatum { get; set; }
        public long Fk_Id_Besitzer { get; set; }
        public string Code { get; set; }

        public virtual Auto Auto1 { get; set; }
        public virtual Auto Auto2 { get; set; }
        public virtual Besitzer Besitzer { get; set; }
    }
}
