//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beispiel_03
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BesitzerEntities2 : DbContext
    {
        public BesitzerEntities2()
            : base("name=BesitzerEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Auto> Auto { get; set; }
        public virtual DbSet<Besitzer> Besitzer { get; set; }
    
        public virtual int AutoEinfuegen(Nullable<long> id, string marke, Nullable<decimal> kilometerstand, Nullable<System.DateTime> herstellungsdatum, Nullable<long> fk_Id_Besitzer)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(long));
    
            var markeParameter = marke != null ?
                new ObjectParameter("Marke", marke) :
                new ObjectParameter("Marke", typeof(string));
    
            var kilometerstandParameter = kilometerstand.HasValue ?
                new ObjectParameter("Kilometerstand", kilometerstand) :
                new ObjectParameter("Kilometerstand", typeof(decimal));
    
            var herstellungsdatumParameter = herstellungsdatum.HasValue ?
                new ObjectParameter("Herstellungsdatum", herstellungsdatum) :
                new ObjectParameter("Herstellungsdatum", typeof(System.DateTime));
    
            var fk_Id_BesitzerParameter = fk_Id_Besitzer.HasValue ?
                new ObjectParameter("Fk_Id_Besitzer", fk_Id_Besitzer) :
                new ObjectParameter("Fk_Id_Besitzer", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AutoEinfuegen", idParameter, markeParameter, kilometerstandParameter, herstellungsdatumParameter, fk_Id_BesitzerParameter);
        }
    
        public virtual ObjectResult<AutosLesen_Result> AutosLesen()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AutosLesen_Result>("AutosLesen");
        }
    
        public virtual ObjectResult<BesitzerLaden_Result> BesitzerLaden()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BesitzerLaden_Result>("BesitzerLaden");
        }
    }
}
